#!/usr/bin/env python3.5

from rdflib import Graph, Namespace, URIRef, Literal
import rdflib
import sys

# parts of brick to load
brick = {
    'BRICK': {
        'file': 'Brick.ttl',
        'namespace': Namespace('http://buildsys.org/ontologies/Brick#'),
        'prefix': 'brick',
    },
    'BRICKFRAME': {
        'file': 'BrickFrame.ttl',
        'namespace': Namespace('http://buildsys.org/ontologies/BrickFrame#'),
        'prefix': 'bf',
    },
    'BRICKTAG': {
        'file': 'BrickTag.ttl',
        'namespace': Namespace('http://buildsys.org/ontologies/BrickTag#'),
        'prefix': 'btag',
    },
}

# guard: command line arguments
if len(sys.argv)!=2:
    print('Syntax: %s PATH_TO_BRICK' % sys.argv[0])
    print('        %s ../../GroundTruth/Brick' % sys.argv[0])
    exit(1)
brickpath = sys.argv[1]

# get started on the graph
g = Graph()

# general namespaces
RDF   = Namespace('http://www.w3.org/1999/02/22-rdf-syntax-ns#')
OWL   = Namespace('http://www.w3.org/2002/07/owl#')
GROUP = Namespace('http://buildsys.org/ontologies/BrickGroup#')
g.parse('brick_group.ttl', format='turtle')
g.bind('rdf', RDF)
g.bind('owl', OWL)
g.bind('grp', GROUP)

# brick namespace
for name in brick:
    g.parse('%s/%s' % (brickpath, brick[name]['file']), format='turtle')
    g.bind(brick[name]['prefix'], brick[name]['namespace'])
    globals()[name] = brick[name]['namespace']

# rotary heat exchanger namespace
RHX = Namespace('http://buildsys.org/ontologies/rotary_heat_exchanger#')
g.bind('rhx', RHX)

# generate group
group   = RHX['group']
port_pi = RHX['port/pi']
port_po = RHX['port/po']
port_si = RHX['port/si']
port_so = RHX['port/so']
g.add( (group  , RDF.type, GROUP.Group) )
g.add( (port_pi, RDF.type, GROUP.Port) )
g.add( (port_po, RDF.type, GROUP.Port) )
g.add( (port_si, RDF.type, GROUP.Port) )
g.add( (port_so, RDF.type, GROUP.Port) )
g.add( (group  , GROUP.labeled, Literal('Rotary Heat Exchanger')) )
g.add( (port_pi, GROUP.labeled, Literal('Primary Input')) )
g.add( (port_po, GROUP.labeled, Literal('Primary Output')) )
g.add( (port_si, GROUP.labeled, Literal('Secondary Input')) )
g.add( (port_so, GROUP.labeled, Literal('Secondary Output')) )

# generate contents definitions
Affects = RHX['relations/affects']
g.add( (Affects, RDF['type'], OWL['ObjectProperty']) )
Side = RHX['types/Side']
g.add( (Side, RDF.type, OWL.Class) )

# generate contents
p = RHX['contents/primary']
s = RHX['contents/secondary']
g.add( (p, RDF.type, Side) )
g.add( (s, RDF.type, Side) )
g.add( (port_pi, BRICKFRAME.feeds, p) )
g.add( (p      , BRICKFRAME.feeds, port_po) )
g.add( (port_si, BRICKFRAME.feeds, s) )
g.add( (s      , BRICKFRAME.feeds, port_so) )
g.add( (p, Affects, s) )

# generate grouping relationships
for entity in [port_pi, port_po, port_si, port_so, p, s]:
    g.add( (entity, GROUP.within, group) )

# store result
print('Number of relations: %u' % (len(g)))
g.serialize('brick_rotary_heat_exchanger.ttl', 'turtle')

